language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
script:
  - pip install -e .
  - py.test --pep8 -m pep8 -n0
  - py.test -n0
  - ./test_pylint
  - python scripts/run_planner.py tri mini
