#!/bin/bash

# Robust way of locating script folder
# from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE=${BASH_SOURCE:-$0}

DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

set -e

PACKAGE=sst_wrapper

time pylint --rcfile=.pylintrc ${PACKAGE}

# Check certain more strict rules on non-tests and sandboxes
time pylint --rcfile=.pylintrc --disable=all --enable=protected-access,invalid-name --ignore-patterns="test_.*,tests_.*,.*_sandbox,sandbox_.*" ${PACKAGE}

# Check documentation
pylint --rcfile=.pylintrc --disable=all --load-plugins=bc_linters.docstring_checker \
    --enable=bc-missing-docstring,bc-empty-docstring,argument-after-return-docstring,return-after-return-docstring,empty-function-description-docstring,missing-argument-docstring,extra-argument-docstring,no-return-docstring,unnecessary-return-docstring,wrong-parameter-order-docstring,duplicate-argument-docstring \
    --ignore-patterns="test_.*,.*_sandbox,sandbox_.*" ${PACKAGE}
